### ISSUE TITLE
Texture upgrade

### ISSUE THREAD

**Issue by roamingBug666** [fabianmontag/voxel#1]
Hey dude, whatsup, so i was looking thru ur project and I thought it is really cool but the textures are kind of um not accurate and too bright, so I swapped em for the real MC textures to spruce it up, hope u like it! If you plan on adding trees or stuff, i got the textures so just ask me if u want
bye
PS: I really recommend u change to vanilla JS, much more supported and accessible and stuff
![textures-3cbbd9f9](https://github.com/fabianmontag/voxel/assets/136437098/49d442ce-799f-4b1d-b7bc-b34fa6fa04f8)
PPS: Why all the whitespace?

**Comment by fabianmontag** [comment]
Hi,
thanks for the effort, but I deliberately chose to not just copy the original MC textures - or any other texture pack for that matter - because I am not sure about the copyright, so I just decided to quickly mix together some basic textures.

What you see is a texture-atlas, where all the textures are put on this one big PNG, which is 512x512 px big, where each texture has a dimension of 32x32, meaning the texture-atlas can fit 256 different textures. Because I only made a few basic ones, the rest of the slots are empty, hence the whitespace.

The application was coded with Typescript, which gets transpiled to JS anyway. I used THREEjs because implementing everything from scratch in WebGL seemed overkill and unnecessary to me, it wasn't something I was interested in anyway.

Because I am currently invested in my [main project](https://github.com/fabianmontag/inkuility), I cant exactly tell you when I will continue with this, but I certainly have planned to do so, this also included to implemented trees etc, this was just a little basic boilerplate, a lot of it isn't final yet.

**Comment by roamingBug666** [comment]
hmm ok but I'm pretty sure you only need to type something like this;
"All textures are 100% copied from Minecraft, property of Mojang/Microsoft, with whom I have no association"
but I'm not really sure, i mean projects like EaglerCraft or MineKhan do that and they've been around for years
I also love ur main project, its rlly cool!
anyway yeah, cool stuff and keep on trucking lol
cheers
